Project 1/force-app/main/default/objects/Mail__c/Mail__c.object-meta.xml
<CustomObject>
    <label>Mail</label>
    <nameField>
        <label>Mail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project 1/force-app/main/default/objects/Mail__c/fields/Delivered_Time__c.field-meta.xml
<CustomField>
    <fullName>Delivered_Time__c</fullName>
    <label>Delivered Time</label>
    <type>DateTime</type>
</CustomField>

Project 1/force-app/main/default/objects/Mail__c/fields/Destination__c.field-meta.xml
<CustomField>
    <fullName>Destination__c</fullName>
    <label>Destination</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Mails</relationshipLabel>
    <relationshipName>Mails</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project 1/force-app/main/default/objects/Mail__c/fields/On_Route__c.field-meta.xml
<CustomField>
    <fullName>On_Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>On Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Mails</relationshipLabel>
    <relationshipName>Mails</relationshipName>
    <type>Lookup</type>
</CustomField>

Project 1/force-app/main/default/objects/Mail__c/fields/Receiver__c.field-meta.xml
<CustomField>
    <fullName>Receiver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Receiver</label>
    <referenceTo>Inhabitant__c</referenceTo>
    <relationshipLabel>Mails</relationshipLabel>
    <relationshipName>Mails</relationshipName>
    <type>Lookup</type>
</CustomField>

Project 1/force-app/main/default/objects/Mail__c/fields/Shipping_To__c.field-meta.xml
<CustomField>
    <fullName>Shipping_To__c</fullName>
    <label>Shipping To</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Project 1/force-app/main/default/objects/Mail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shipping</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Out for Delivery</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Missing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project 1/force-app/main/default/objects/Mail__c/fields/Tracking_Code__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Code__c</fullName>
    <label>Tracking Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Project 1/force-app/main/default/objects/Mail__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Value of the package</description>
    <inlineHelpText>The value of a package can be 100 dollars.</inlineHelpText>
    <label>Value</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Project 1/force-app/main/default/classes/TrackingWizard.cls
public class TrackingWizard {
    public String tCode {get;set;}
    public String errorMessage {get;set;}
    public Mail__c mailPackage{get;set;}
    
   public pagereference page1_next(){
			if(tCode !=''){
                try{
                    mailPackage = [SELECT Name, Delivered_Time__c,Destination__c, On_Route__c, Receiver__c,Shipping_To__c,Status__c,Tracking_Code__c,Value__c FROM Mail__c WHERE Tracking_Code__c =: tCode];
                }catch(Exception e){
                    errorMessage = 'ERROR: Can\'t find a Package with that tracking code!!';
                    return page.TrackingWizardPage1;
                }
            }
       		else{
           		errorMessage = 'ERROR: Please enter a tracking code!!';
           		return page.TrackingWizardPage1;
       		}
        errorMessage = '';
        tCode = '';
        return page.TrackingWizardPage2;
    }
    public pagereference page2_previous(){
        mailPackage = null;
        return page.TrackingWizardPage1;
    }
    
}