Project 1/force-app/main/default/objects/Inhabitant__c/Inhabitant__c.object-meta.xml
<CustomObject>
    <label>Inhabitant</label>
    <nameField>
        <label>Inhabitant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inhabitants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project 1/force-app/main/default/objects/Inhabitant__c/fields/Inhabitant_Contact__c.field-meta.xml
<CustomField>
    <fullName>Inhabitant_Contact__c</fullName>
    <label>Inhabitant Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Inhabitants</relationshipLabel>
    <relationshipName>Inhabitants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project 1/force-app/main/default/objects/Mail__c/Mail__c.object-meta.xml
<CustomObject>
    <label>Mail</label>
    <nameField>
        <label>Mail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project 1/force-app/main/default/objects/Mail__c/fields/Delivered_Time__c.field-meta.xml
<CustomField>
    <fullName>Delivered_Time__c</fullName>
    <label>Delivered Time</label>
    <type>DateTime</type>
</CustomField>

Project 1/force-app/main/default/objects/Mail__c/fields/On_Route__c.field-meta.xml
<CustomField>
    <fullName>On_Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>On Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Mails</relationshipLabel>
    <relationshipName>Mails</relationshipName>
    <type>Lookup</type>
</CustomField>

Project 1/force-app/main/default/objects/Mail__c/fields/Receiver__c.field-meta.xml
<CustomField>
    <fullName>Receiver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Receiver</label>
    <referenceTo>Inhabitant__c</referenceTo>
    <relationshipLabel>Mails</relationshipLabel>
    <relationshipName>Mails</relationshipName>
    <type>Lookup</type>
</CustomField>

Project 1/force-app/main/default/objects/Mail__c/fields/Shipping_To__c.field-meta.xml
<CustomField>
    <fullName>Shipping_To__c</fullName>
    <label>Shipping To</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Project 1/force-app/main/default/objects/Mail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shipping</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Out for Delivery</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Missing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project 1/force-app/main/default/objects/Mail__c/fields/Tracking_Code__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Code__c</fullName>
    <label>Tracking Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Project 1/force-app/main/default/objects/Mail__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Value of the package</description>
    <inlineHelpText>The value of a package can be 100 dollars.</inlineHelpText>
    <label>Value</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Project 1/force-app/main/default/classes/MailPackageController.cls
public class MailPackageController {    
    
    Map<String,String> session = Auth.SessionManagement.getCurrentSession();
    String userID = session.get('UsersId');
    public List<Contact> contacts {get;set;}
    public List<Inhabitant__c> inhabitants {get;set;}
    public List<Mail__c> userMails {get;set;}

    public MailPackageController() {
        //we have USERID
     	//select all contacts where contact.owner ID == userID
     	// for this list, select all inhabitants that each contact owns, and push their mails into a list
     	contacts = [SELECT id FROM Contact WHERE ownerID =: userID ];
        inhabitants = new List<Inhabitant__c>();
        userMails = new List<Mail__c>();
        
        for(Contact con:contacts){
            for(Inhabitant__c inhab:[SELECT id FROM Inhabitant__c WHERE Inhabitant_Contact__c =: con.id]){
                inhabitants.add(inhab);
            }
        }        
        
        for(Inhabitant__c inhab:inhabitants){
            for(Mail__c mail:[SELECT name, on_route__c, Shipping_to__c, Receiver__c, Tracking_Code__c, Status__c, Delivered_Time__c, Value__c FROM Mail__c WHERE Receiver__c =: inhab.id]){
                userMails.add(mail);
            }
        }
        
        
        
    }
    
    
} //end of controller